### ISSUE TITLE
Idempotency

### ISSUE THREAD

**Issue by mooky31** [fortinet/ansible-fortimanager-generic#10]
Hello,

I'm trying to declare a new device using this module.
Here is the playbook:
```
- name: Test API
  hosts: FortiManager
  gather_facts: no
  connection: httpapi

  collections:
    - fortinet.fortimanager


  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443

  tasks:
    - name: Provisioning
      fmgr_generic:
         method: exec
         params:
            -  url: /dvm/cmd/add/device
               data:
                  adom: root
                  device:
                     desc: Provisioned by ansible
                     device action: add_model
                     mgmt_mode: fmg
                     mr: 2
                     name: fortiVM01
                     os_type: fos
                     os_ver: '6.0'
                     sn: FGVMEVHBR3TXNV04
                  flags:
                    - none
      register: provision
      failed_when: provision.rc != -20010
```
The task fails if the device already exists, whereas it should be OK.

But as this is a generic module I can understand this behavior.
I tried to correct it myself, but the ```failed_when``` doesn't do anything, I don't know why

**Comment by chillancezen** [comment]
hi @mooky31,

it seems that you are using ansible 2.9.x, the syntax is not recognized correctly.

according to https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html, 

the syntax is a little different in old version of Ansible: **we should add another task to detect the errors if we are going to override the way to check errors**

```
- name: Test API
  hosts: fortimanager01
  gather_facts: no
  connection: httpapi

  collections:
    - fortinet.fortimanager


  vars:
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443

  tasks:
    - name: Provisioning
      fmgr_generic:
         method: exec
         params:
            -  url: /dvm/cmd/add/device
               data:
                  adom: root
                  device:
                     desc: Provisioned by ansible
                     device action: add_model
                     mgmt_mode: fmg
                     mr: 2
                     name: fortiVM01
                     os_type: fos
                     os_ver: '6.0'
                     sn: FGVMEVHBR3TXNV04
                  flags:
                    - none
      register: provision
      ignore_errors: yes

    - name: fail the play
      fail:
        msg: "the ... fail"
      failed_when: provision.rc != 0 and provision.rc != -20010
```

** remember to ignore all errors for the fist task**

thanks,
Link
